// Development-only seed data. NEVER import this file from frontend production code.
// Use `npm run seed:dev` locally to run the seed script (it will refuse to run in production).

exports.INITIAL_DEALERS = [
  {
    id: 'auto-choice-peshawar',
    name: 'Auto Choice Showroom',
    avatarLetter: 'AC',
    subtitle: 'Premium Pre-Owned & Luxury Vehicles',
    location: 'Ring Road Peshawar, KP, Pakistan',
    phone: '03149198403',
    whatsapp: '923149198403',
    email: 'autochoice.peshawar@gmail.com',
    rating: 4.9,
    vehiclesCount: 6,
    followersCount: '1.2K',
    coverImage: 'https://images.unsplash.com/photo-1562141961-b5d06412a893?auto=format&fit=crop&q=80&w=1200',
    description: "Auto Choice Showroom is Peshawar's elite automotive hub, specializing in high-quality pre-owned vehicles, luxury hybrid SUVs, and reliable family sedans. Certified inspections and absolute transparency.",
    slug: 'auto-choice',
    theme_choice: 'Bone',
    verified: true,
    socials: {
      facebook: 'https://facebook.com/autochoice',
      instagram: 'https://instagram.com/autochoice',
      whatsapp: 'https://wa.me/923149198403'
    },
    activityFeed: []
  }
];

exports.INITIAL_LISTINGS = [
  {
    id: 'toyota-corolla-grande-2020',
    title: '2020 Toyota Corolla Altis Grande 1.8 CVT-i',
    make: 'Toyota',
    model: 'Corolla',
    year: 2020,
    price: 5600000,
    mileage: 62000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-cc34a364650e?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Beautiful total genuine Corolla Grande 1.8 CVT-i in immaculate condition. Registered in Lahore, single owner, extremely clean exterior and interior. Fitted with high-end premium leather seats, sunroof, cruise control, dual-zone climate system and original infotainment screen. Complete documents available.',
    createdAt: new Date().toISOString(),
    tags: ['Toyota', 'Corolla', 'Grande', 'Sedan'],
    specs: { color: 'Super White', engineSize: '1800 CC', horspower: '138 HP', regionalSpecs: 'Local Assembly' },
    condition: 'Used',
    engineCC: 1800,
    exteriorColor: 'Super White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Lahore',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1621007947382-cc34a364650e?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['Sunroof', 'Leather Seats', 'Cruise Control', 'Reverse Camera', 'Push Start']
  },
  {
    id: 'haval-h6-hev-2024',
    title: '2024 Haval H6 HEV (Hybrid)',
    make: 'Haval',
    model: 'H6',
    year: 2024,
    price: 11200000,
    mileage: 8500,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Latest model 2024 Haval H6 Hybrid (HEV). Zero errors, scratchless pearl sky blue finish. Loaded with Level 2 Autonomous ADAS safety features, 360 camera view, electronic panoramic sunroof, lane assist, auto park assist, dual screen interface, ambient lighting, and electronic tailgate. Exceptionally fuel efficient (up to 20 km/L).',
    createdAt: new Date().toISOString(),
    tags: ['Haval', 'H6', 'HEV', 'SUV'],
    specs: { color: 'Sky Blue', engineSize: '1500 CC', horspower: '243 HP', regionalSpecs: 'Local Assembly' },
    condition: 'Used',
    engineCC: 1500,
    exteriorColor: 'Sky Blue',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Peshawar',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['Level 2 ADAS', 'Panoramic Sunroof', '360 Camera', 'Heated & Cooled Seats', 'Electric Tailgate']
  },
  {
    id: 'honda-civic-rs-2026',
    title: '2026 Honda Civic RS Turbo',
    make: 'Honda',
    model: 'Civic',
    year: 2026,
    price: 9800000,
    mileage: 1200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Practically brand new 2026 Honda Civic RS Turbo. Red accents with original Crystal Black finish. High-performance 1.5L VTEC Turbo engine, Honda SENSING suite (Collision Mitigation Braking, Lane Keep Assist, Lead Car Notification, Adaptive Cruise Control), sport mode, RS body styling, dual exhausts, premium Bose audio system.',
    createdAt: new Date().toISOString(),
    tags: ['Honda', 'Civic', 'RS', 'Sedan'],
    specs: { color: 'Crystal Black', engineSize: '1500 CC', horspower: '176 HP', regionalSpecs: 'Local Assembly' },
    condition: 'New',
    engineCC: 1500,
    exteriorColor: 'Crystal Black',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['Honda SENSING', 'RS Sport Trim', 'Sunroof', 'Digital Cockpit', '18" Matte Black Alloys']
  },
  {
    id: 'honda-civic-oriel-2025',
    title: '2025 Honda Civic VTi Oriel Turbo',
    make: 'Honda',
    model: 'Civic',
    year: 2025,
    price: 8600000,
    mileage: 14000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Beautiful white 2025 Honda Civic VTi Oriel 1.5L Turbo. First-hand owned, fully maintained through authorized Honda dealerships. Bumper-to-bumper genuine paint, immaculate ivory leather interior, digital instrument panel, slide sunroof, parking sensors, hill assist control, and excellent fuel economy.',
    createdAt: new Date().toISOString(),
    tags: ['Honda', 'Civic', 'Oriel', 'Sedan'],
    specs: { color: 'Taffeta White', engineSize: '1500 CC', horspower: '127 HP', regionalSpecs: 'Local Assembly' },
    condition: 'Used',
    engineCC: 1500,
    exteriorColor: 'Taffeta White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Lahore',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['Sunroof', 'Leather Upholstery', 'Climate Control', 'Keyless Entry', 'Retractable Mirrors']
  },
  {
    id: 'honda-deluxe-125-2014',
    title: '2014 Honda Deluxe 125',
    make: 'Honda',
    model: 'Deluxe 125',
    year: 2014,
    price: 180000,
    mileage: 42000,
    fuelType: 'Petrol',
    transmission: 'Manual',
    imageUrl: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: false,
    dealerId: 'auto-choice-peshawar',
    description: 'Extremely well-maintained 2014 Honda Deluxe 125. Classic red finish, original engine with crisp sound and robust pull, 5-speed manual transmission, disk brake setup, powerful headlight, original indicators, smooth suspension. Clean registration, tax lifetime paid.',
    createdAt: new Date().toISOString(),
    tags: ['Honda', 'Deluxe', 'Motorcycle', 'Bike'],
    specs: { color: 'Cherry Red', engineSize: '125 CC', horspower: '11 HP', regionalSpecs: 'Local Assembly' },
    condition: 'Used',
    engineCC: 125,
    exteriorColor: 'Cherry Red',
    bodyCondition: 'Minor Touch-ups',
    registrationCity: 'Karachi',
    documentType: 'Original Book',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['5-Speed Manual Gearbox', 'Front Disc Brake', 'Self Start', 'Chrome Accents']
  },
  {
    id: 'suzuki-wagon-r-2013',
    title: '2013 Suzuki Wagon R ENE-Charge',
    make: 'Suzuki',
    model: 'Wagon R',
    year: 2013,
    price: 2450000,
    mileage: 89000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=1200',
    verified: true,
    approved: true,
    featured: false,
    dealerId: 'auto-choice-peshawar',
    description: 'Excellent condition 2013 Suzuki Wagon R imported model with advanced ENE-Charge hybrid assist battery technology. Exceptional city fuel economy of 22 km/L. Silky Silver exterior, neat and clean fabric seats, climate control, push start, radar brake support, pristine automatic transmission.',
    createdAt: new Date().toISOString(),
    tags: ['Suzuki', 'Wagon R', 'ENE-Charge', 'Hatchback'],
    specs: { color: 'Silky Silver', engineSize: '660 CC', horspower: '52 HP', regionalSpecs: 'Imported' },
    condition: 'Used',
    engineCC: 660,
    exteriorColor: 'Silky Silver',
    bodyCondition: 'Minor Touch-ups',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=1200'],
    sellerPhone: '03149198403',
    sellerWhatsApp: '923149198403',
    sellerName: 'Auto Choice Showroom',
    sellerType: 'Showroom',
    status: 'Available',
    features: ['ENE-Charge System', 'Radar Braking Support', 'Push Button Start', 'Climate Control']
  }
];

exports.INITIAL_REVIEWS = {
  'auto-choice-peshawar': [
    {
      id: 'rev-1',
      author: 'Kamran Shah',
      rating: 5,
      comment: 'Excellent dealing and complete transparent process! Highly recommended Auto Choice.',
      date: new Date().toISOString()
    }
  ]
};
