import { Dealer, CarListing, Review } from './types';

export const INITIAL_DEALERS: Dealer[] = [
  {
    id: 'auto-choice-peshawar',
    name: 'Auto Choice - The Right Choice',
    avatarLetter: 'AC',
    coverImage: '/src/assets/images/auto_choice_showroom_1783593399914.jpg',
    avatarUrl: '/src/assets/images/auto_choice_logo_1784465631235.jpg',
    logo: '/src/assets/images/auto_choice_logo_1784465631235.jpg',
    subtitle: 'To buy and Sell New and Used Cars, Jeeps and SUVs',
    location: 'Alamas Car Village, Ring Road, Peshawar',
    rating: 4.9,
    vehiclesCount: 12,
    followersCount: '5.6k',
    flagshipVerified: true,
    description: 'Auto Choice is a premier automotive marketplace specialized in buying and selling immaculate new and used cars, robust jeeps, and luxury premium SUVs. Committed to absolute transparency, nationwide delivery, and personalized customer service all over Pakistan.',
    phone: '+923159085086',
    whatsapp: '923159085086',
    contactPerson: 'Malak Mazhar',
    // @ts-ignore
    ownerName: 'Malak Mazhar',
    // @ts-ignore
    officialEmail: 'Mazharsouls@gmail.com',
    // @ts-ignore
    email: 'Mazharsouls@gmail.com',
    socials: {
      tiktok: 'https://www.tiktok.com/@grandautochoice',
      instagram: 'https://instagram.com/autochoice',
      website: null
    },
    activityFeed: [
      {
        id: 'act-ac-1',
        timestamp: '1 hour ago',
        badge: 'SUV Special',
        imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI',
        title: 'Toyota Fortuner Legender 2023',
        description: 'Immaculate white Fortuner Legender. Standard high performance and luxury KPK registered. Call Malak Mazhar for direct offers.',
        price: 'Rs. 18,500,000',
        carId: 'car-fortuner-legender',
      }
    ]
  }
];

export const INITIAL_LISTINGS: CarListing[] = [
  {
    id: 'car-porsche-911-gt3',
    title: '2023 Porsche 911 GT3',
    make: 'Porsche',
    model: '911 GT3',
    year: 2023,
    price: 85000000,
    mileage: 15000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBZtBmgc7whl0zLeKAWRQtQFFaqpX0BeFFFhv-7s4eS0XJv8a1i88YYMhBhIwgqiGj0A7rd6ANHhOigA9qyoVbvYOAnweQXtNq7ErLbCyQjxwaBqRacvP9ywt_OdSJTgjIghQ1HJJryxlmkvysweO35ZG8mIQ-GXkXc9eRcG8W6mfooetlurMVEfJwBT5kA3gsemMgkdQQ1x8uV6kvo-7Fd2TWs0eo0DbfHCrGCCkwIOepT-cmfMIReSrrjlnJsv7mXR0lNxmLRanQ',
    verified: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Astonishing 2023 Porsche 911 GT3 in pristine, unmodified showroom state. Extravagantly optioned with metallic dark gray outer coat, carbon-ceramic brakes, Clubsport safety cage, carbon fiber bucket seats, and telemetry monitors. Pre-certified under 111-point professional audit.',
    createdAt: '2026-06-12T10:00:00Z',
    tags: ['SUV', 'Luxury', 'Classic', 'Sport'],
    specs: {
      color: 'Dark Metallic Gray',
      engineSize: '4.0L H6',
      horspower: '502 hp',
      regionalSpecs: 'Imported Spec (Pak Registered)'
    },
    condition: 'Used',
    engineCC: 4000,
    exteriorColor: 'Dark Metallic Gray',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Karachi',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuBZtBmgc7whl0zLeKAWRQtQFFaqpX0BeFFFhv-7s4eS0XJv8a1i88YYMhBhIwgqiGj0A7rd6ANHhOigA9qyoVbvYOAnweQXtNq7ErLbCyQjxwaBqRacvP9ywt_OdSJTgjIghQ1HJJryxlmkvysweO35ZG8mIQ-GXkXc9eRcG8W6mfooetlurMVEfJwBT5kA3gsemMgkdQQ1x8uV6kvo-7Fd2TWs0eo0DbfHCrGCCkwIOepT-cmfMIReSrrjlnJsv7mXR0lNxmLRanQ'],
    assemblyType: 'Imported',
    dentPaintDescription: 'Pristine exterior, zero dents or scratches.',
    tokenTaxStatus: 'Paid',
    topSpeed: '193 mph',
    acceleration: '3.2s',
    range: '450 km'
  },
  {
    id: 'car-mercedes-g63',
    title: '2024 Mercedes-Benz G63 AMG',
    make: 'Mercedes-Benz',
    model: 'G63 AMG',
    year: 2024,
    price: 115000000,
    mileage: 500,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI',
    verified: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Practically delivery mileage, raw 2024 model year Mercedes Benz G63 AMG. Painted in bespoke matte Obsidian Black with carbon accent elements. Extravagant diamond-stitched red leather interiors. Absolute peak executive presence with extreme safety and double exhaust options.',
    createdAt: '2026-06-13T15:00:00Z',
    tags: ['SUV', 'Luxury'],
    specs: {
      color: 'Matte Obsidian Black',
      engineSize: '4.0L V8 BiTurbo',
      horspower: '577 hp',
      regionalSpecs: 'Imported Spec (Pak Registered)'
    },
    condition: 'Used',
    engineCC: 4000,
    exteriorColor: 'Matte Obsidian Black',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Lahore',
    documentType: 'Original Book',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI'],
    assemblyType: 'Imported',
    dentPaintDescription: 'Total original paint, scratchless showroom condition.',
    tokenTaxStatus: 'Paid',
    topSpeed: '149 mph',
    acceleration: '4.5s',
    range: '550 km'
  },
  {
    id: 'car-bmw-m4-comp',
    title: '2022 BMW M4 Competition',
    make: 'BMW',
    model: 'M4 Competition',
    year: 2022,
    price: 30100000,
    mileage: 12000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBkRyZgqdwVho1YG4awPp4toJiKUSqH05IGmlCDeY-esoL_rsDYbAkp7FPKlnXbFzCmNSSrCuHqwrXO_non2l8_jM8QfzbMxg4aYyOMfOsMhs3rpT2R8j1Gx1Mf3knoB5B5hIqUiVq3mIkhn8Bc_376AboW7iBngDAdVbQRCj0uupxH2V2RrluMiTA106UgPdQQb-5gB_A5arpTkTHIfrGwAj737v9D8LD8iIwl-xWDtVKgoKbuQ9XpeQ3NVP4I-N1tqLxV1YsPjWs',
    verified: true,
    featured: false,
    dealerId: 'auto-choice-peshawar',
    description: 'Immaculately customized 2022 BMW M4 Competition model in Alpine White. Equipped with adaptive sports suspension, carbon aerodynamic wings, laser lamps, and supreme interior comfort metrics.',
    createdAt: '2026-06-10T12:00:00Z',
    tags: ['Sedan', 'Luxury', 'Sport'],
    specs: {
      color: 'Alpine White',
      engineSize: '3.0L S58 Twin-Turbo I6',
      horspower: '503 hp',
      regionalSpecs: 'Imported Spec'
    },
    condition: 'Used',
    engineCC: 3000,
    exteriorColor: 'Alpine White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Islamabad',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuBkRyZgqdwVho1YG4awPp4toJiKUSqH05IGmlCDeY-esoL_rsDYbAkp7FPKlnXbFzCmNSSrCuHqwrXO_non2l8_jM8QfzbMxg4aYyOMfOsMhs3rpT2R8j1Gx1Mf3knoB5B5hIqUiVq3mIkhn8Bc_376AboW7iBngDAdVbQRCj0uupxH2V2RrluMiTA106UgPdQQb-5gB_A5arpTkTHIfrGwAj737v9D8LD8iIwl-xWDtVKgoKbuQ9XpeQ3NVP4I-N1tqLxV1YsPjWs'],
    assemblyType: 'Imported',
    dentPaintDescription: 'Front bumper has slight scratch but overall completely original.',
    tokenTaxStatus: 'Paid',
    topSpeed: '180 mph',
    acceleration: '3.7s',
    range: '500 km'
  },
  {
    id: 'car-audi-rsq8',
    title: '2021 Audi RS Q8',
    make: 'Audi',
    model: 'RS Q8',
    year: 2021,
    price: 38900000,
    mileage: 24000,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI',
    verified: false,
    featured: false,
    dealerId: 'auto-choice-peshawar',
    description: 'Outstanding 2021 Audi RS Q8 with pristine gray body configuration. Features Nappa leather seats, dynamic active chassis, massage nodes, and incredible V8 grunt.',
    createdAt: '2026-06-08T09:00:00Z',
    tags: ['SUV', 'Luxury'],
    specs: {
      color: 'Nardo Gray',
      engineSize: '4.0L twin-turbocharged V8',
      horspower: '591 hp',
      regionalSpecs: 'Imported Spec'
    },
    condition: 'Used',
    engineCC: 4000,
    exteriorColor: 'Nardo Gray',
    bodyCondition: 'Minor Touch-ups',
    registrationCity: 'Lahore',
    documentType: 'Duplicate',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI'],
    assemblyType: 'Imported',
    dentPaintDescription: 'Slight bumper touchups, side fenders completely original.',
    tokenTaxStatus: 'Paid',
    topSpeed: '155 mph',
    acceleration: '3.8s',
    range: '600 km'
  },
  {
    id: 'car-porsche-911-carrera',
    title: '2023 Porsche 911 Carrera S',
    make: 'Porsche',
    model: '911 Carrera S',
    year: 2023,
    price: 45700000,
    mileage: 8200,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHs7Za22_aYMs1VGHEYckNGnFgDZzkirSxzLiCJBbCB2xad7rRbbQo7M1xi7RyGNq8fvUUeGKfFFf93rh8AmKvNpWDRSLWCByW_bP0wK9XhH89wGXq5pXT2Px4I9jvkv5MBaJz82g9lonJQn3tomdmnq1xkOb7_VYzNv57n_oDsol7EzCfdb7PAysiZ_xKKaKLUSX2asp4D15fPMkZ87Rak4ev3Dn7scIHsYk-rDEk0lhfaS18RDIBh_FH8gp3SYVfy_24Oiv87Uw',
    verified: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Unbelievable driving dynamics from this Porsche 911 Carrera S. Clean history, low mileage, pre-inspected by Almas certified mechanics.',
    createdAt: '2026-06-14T09:30:00Z',
    tags: ['Classic', 'Luxury', 'Sport'],
    specs: {
      color: 'Chalk White',
      engineSize: '3.0L Twin-Turbo Flat-6',
      horspower: '443 hp',
      regionalSpecs: 'Imported Spec'
    },
    condition: 'Used',
    engineCC: 3000,
    exteriorColor: 'Chalk White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Lahore',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuBHs7Za22_aYMs1VGHEYckNGnFgDZzkirSxzLiCJBbCB2xad7rRbbQo7M1xi7RyGNq8fvUUeGKfFFf93rh8AmKvNpWDRSLWCByW_bP0wK9XhH89wGXq5pXT2Px4I9jvkv5MBaJz82g9lonJQn3tomdmnq1xkOb7_VYzNv57n_oDsol7EzCfdb7PAysiZ_xKKaKLUSX2asp4D15fPMkZ87Rak4ev3Dn7scIHsYk-rDEk0lhfaS18RDIBh_FH8gp3SYVfy_24Oiv87Uw'],
    assemblyType: 'Imported',
    dentPaintDescription: 'Total genuine paint, pristine condition.',
    tokenTaxStatus: 'Paid',
    topSpeed: '182 mph',
    acceleration: '4.0s',
    range: '480 km'
  },
  {
    id: 'car-fortuner-legender',
    title: '2023 Toyota Fortuner Legender',
    make: 'Toyota',
    model: 'Fortuner Legender',
    year: 2023,
    price: 18500000,
    mileage: 12000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwfdjDTe-dg6nn_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI',
    verified: true,
    featured: true,
    dealerId: 'auto-choice-peshawar',
    description: 'Toyota Fortuner Legender in absolute top pristine condition. Underwritten with detailed pre-inspection, registered in Peshawar. Active contacts: Malak Mazhar (03159085086).',
    createdAt: '2026-06-14T08:00:00Z',
    tags: ['SUV', 'Luxury'],
    specs: {
      color: 'Super White',
      engineSize: '2.8L Diesel',
      horspower: '201 hp',
      regionalSpecs: 'Pak/Japanese Specs'
    },
    condition: 'Used',
    engineCC: 2800,
    exteriorColor: 'Super White',
    bodyCondition: 'Total Genuine',
    registrationCity: 'Peshawar',
    documentType: 'Smart Card',
    tokenTaxPaid: true,
    images: ['https://lh3.googleusercontent.com/aida-public/AB6AXuDJqJ3MkFiS7DRa6OqXFSkJcsI3cZ9685e7vJevGiglSWNC2IfxmZhySZymL0jE7nrtUXMK6mf7aHDMHqlrZWKmkCE0srhAhIAspnSs8zwspan_Aga0qdRS4HRXFWY3F_q8ZawA6LnWHg_skTG6XUMyQyjW-p2_o3ang_YT0dQhOTTRaDaYBO7_Qu4gbU9bE6JvdTXnmdtv7C205mCo97G1dOgK0FxT0Ydptt8zcbWU1l6sXYT9tEUyNWIkdrgiPIn9esI'],
    assemblyType: 'Local',
    dentPaintDescription: 'Spotless, bumper to bumper total genuine.',
    tokenTaxStatus: 'Paid',
    topSpeed: '115 mph',
    acceleration: '9.5s',
    range: '750 km'
  }
];

export const INITIAL_REVIEWS: Record<string, Review[]> = {
  'auto-choice-peshawar': [
    {
      id: 'rev-ac-1',
      author: 'Shahid Khan',
      rating: 5,
      date: 'June 14, 2026',
      comment: 'Excellent deal on a Land Cruiser. Malak Mazhar and the team are absolute professionals. The car is exactly as described!'
    },
    {
      id: 'rev-ac-2',
      author: 'Inam-ur-Rehman',
      rating: 5,
      date: 'June 11, 2026',
      comment: 'Very straightforward buying process. Bought a clean Hilux Revo and got it delivered nationwide to Islamabad within 24 hours. Highly trustable.'
    },
    {
      id: 'rev-1',
      author: 'Amjid B.',
      rating: 5,
      date: 'June 10, 2026',
      comment: 'Absolutely superb service from Auto Choice. From initial inquiry to personalized delivery in Lahore, everything was handled professionally. Highly recommended dealership!'
    },
    {
      id: 'rev-2',
      author: 'Fatima K.',
      rating: 4,
      date: 'May 24, 2026',
      comment: 'Very reliable pre-owned collection. Got my Carrera inspected through BAZAR360 inspection service too and it was super easy!'
    },
    {
      id: 'rev-3',
      author: 'Zayed A.',
      rating: 5,
      date: 'June 13, 2026',
      comment: 'Top tier sports car selection. The Porsche 911 GT3 is an absolute rocket. Seamless transition.'
    }
  ]
};
